### ISSUE TITLE
Email Attachments have no name.

### ISSUE THREAD

**Issue by jeffreypkelly** [gvandela/MeteorRpiReceiver#1]
Gio,

Love this program and get terrific results. I run it on a Tinker Board.
I realized that the attachments sent via email don't have a filename.
Is there a way in the code to add the file name to each attachment? 
I am running into trouble with my usage without having a file name on the attachments.

TY

Jeff
K2SDR
jkelly@verizon.net

**Comment by gvandela** [comment]
Solved by adding your proposed code. Thanks!
