### ISSUE TITLE
I added some code

### ISSUE THREAD

**Issue by jeffreypkelly** [gvandela/MeteorRpiReceiver#3]
If you replace these two sections, with this code, the attachments will now have the proper filename:

     	image_122 = os.path.join(main_folder, 'Images', file_name + '_122.jpg')
		fp = open(image_122, 'rb')
		img = MIMEImage(fp.read())
		fp.close()
            img.add_header('Content-Disposition', 'attachment', filename=file_name + '_122.jpg')
		msg.attach(img)

		image_555 = os.path.join(main_folder, 'Images', file_name + '_555_IR.jpg')
		fp = open(image_555, 'rb')
		img = MIMEImage(fp.read())
		fp.close()
            img.add_header('Content-Disposition', 'attachment', filename=file_name + '_555_IR.jpg')
		msg.attach(img)

Jeff
K2SDR

**Comment by gvandela** [comment]
Worked like a charm. Thanks!
