### ISSUE TITLE
[R82XX] PLL not locked!

### ISSUE THREAD

**Issue by t3chn1ca** [gvandela/MeteorRpiReceiver#6]
Hi gvandela,

Thanks for creating the scripts and making them accessible to us.

I got the install done got all the libraries installed, I am hitting an error "PLL not locked"
on my RTL2832U. I am inferring that the frequency range is not within the lockable range of RTL2832U?

error log:
pi@sdr:~/MeteorRpiReceiver $ /usr/bin/python /home/pi/MeteorRpiReceiver/GRC/METEOR_M2_v04_noGUI.py
gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.10
built-in source types: file osmosdr fcd rtl rtl_tcp rfspace redpitaya 
Using device #0 Generic RTL2832U SN: 77771111153705700
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
[R82XX] PLL not locked!
Press Enter to quit: 

137.903Mhz is within the range of RTL2832U,  Do you have any thoughts on this please?

Thanks
Sachin

**Comment by gvandela** [comment]
Hi Sachin,
Only noticed your message now, sorry for the late reply.
I hadn't noticed this message before, but according to "the internet" it appears to be a fluke. The PLL should lock at some point, as we are indeed well within the tuning range of the tuner.
So, this is in fact not an error. "Press enter to quit" just means the GRC script will run indefinitely, until it's terminated by a user or a script maybe.
So it actually looks like all is working fine ;)

Cheers,
Gio
